import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { UploadIcon } from 'lucide-react';

import {
  SidebarInset,
  SidebarProvider,
} from '@/components/animate-ui/components/radix/sidebar';
import {
  addFileToFolderById,
  createWorkspaceFolders,
  findFileById,
  findFilePathById,
  findFolderById,
  findFolderPathById,
  type WorkspaceFile,
  type WorkspaceFolder,
} from '@/data/sidebarNavigation';
import { FileWorkspace } from '@/features/file-page/FileWorkspace';
import { WorkspaceSidebar } from './features/sidebar/WorkspaceSidebar';
import { useFilePages } from './hooks/useFilePages';
import type { FilePageState } from '@/types/filePage';

const WORKSPACE_FOLDERS_STORAGE_KEY = 'weave:workspace-folders:v1';
const GENERATED_WORKSPACE_FOLDER_PREFIX = 'worker-output-folder:';
const GENERATED_WORKSPACE_FILE_PREFIX = 'worker-output-file:';

function upsertGeneratedFolderChildren(
  folders: WorkspaceFolder[],
  parentFolderId: string,
  generatedChildren: WorkspaceFolder[],
): WorkspaceFolder[] {
  return folders.map((folder) =>
    folder.id === parentFolderId
      ? {
          ...folder,
          children: [
            ...folder.children.filter(
              (child) => !generatedChildren.some((generatedChild) => generatedChild.id === child.id),
            ),
            ...generatedChildren,
          ],
        }
      : {
          ...folder,
          children: upsertGeneratedFolderChildren(folder.children, parentFolderId, generatedChildren),
        },
  );
}

function buildGeneratedWorkspaceFolder(
  fileId: string,
  node: FilePageState['nodes'][number],
): WorkspaceFolder {
  const files: WorkspaceFile[] = (node.contentItems ?? [])
    .filter((item) => item.kind === 'file')
    .map((item) => ({
      id: `worker-output-file:${fileId}:${item.id}`,
      label: item.label,
      description: 'AI-ready output generated by a connected worker.',
      kind: 'brief',
    }));
  const children = (node.contentItems ?? [])
    .filter((item) => item.kind === 'folder')
    .map((item) => ({
      id: `worker-output-folder:${fileId}:${item.id}`,
      label: item.label,
      files: [],
      children: [],
    }));

  return {
    id: `worker-output-folder:${fileId}:${node.id}`,
    label: node.label,
    files,
    children,
  };
}

function mergeWorkerOutputsIntoFolders(
  folders: WorkspaceFolder[],
  pages: Record<string, FilePageState>,
): WorkspaceFolder[] {
  let nextFolders = folders;

  Object.entries(pages).forEach(([fileId, page]) => {
    const fileMatch = findFileById(folders, fileId);

    if (!fileMatch) {
      return;
    }

    const generatedFolders = page.nodes
      .filter(
        (node) =>
          node.kind === 'folder' &&
          node.generatedByWorkerId &&
          (node.contentItems?.length ?? 0) > 0,
      )
      .map((node) => buildGeneratedWorkspaceFolder(fileId, node));

    if (generatedFolders.length === 0) {
      return;
    }

    nextFolders = upsertGeneratedFolderChildren(nextFolders, fileMatch.folderId, generatedFolders);
  });

  return nextFolders;
}

function stripGeneratedWorkspaceEntries(folders: WorkspaceFolder[]): WorkspaceFolder[] {
  return folders
    .filter((folder) => !folder.id.startsWith(GENERATED_WORKSPACE_FOLDER_PREFIX))
    .map((folder) => ({
      ...folder,
      files: folder.files.filter((file) => !file.id.startsWith(GENERATED_WORKSPACE_FILE_PREFIX)),
      children: stripGeneratedWorkspaceEntries(folder.children),
    }));
}

function normalizeWorkspaceFileKind(value: unknown): WorkspaceFile['kind'] {
  return value === 'canvas' || value === 'memo' || value === 'outline' ? value : 'brief';
}

function normalizeWorkspaceFile(value: unknown): WorkspaceFile | null {
  if (
    typeof value !== 'object' ||
    value === null ||
    typeof (value as WorkspaceFile).id !== 'string' ||
    typeof (value as WorkspaceFile).label !== 'string' ||
    typeof (value as WorkspaceFile).description !== 'string'
  ) {
    return null;
  }

  return {
    id: (value as WorkspaceFile).id,
    label: (value as WorkspaceFile).label,
    description: (value as WorkspaceFile).description,
    kind: normalizeWorkspaceFileKind((value as WorkspaceFile).kind),
  };
}

function normalizeWorkspaceFolder(value: unknown): WorkspaceFolder | null {
  if (
    typeof value !== 'object' ||
    value === null ||
    typeof (value as WorkspaceFolder).id !== 'string' ||
    typeof (value as WorkspaceFolder).label !== 'string' ||
    !Array.isArray((value as WorkspaceFolder).children) ||
    !Array.isArray((value as WorkspaceFolder).files)
  ) {
    return null;
  }

  return {
    id: (value as WorkspaceFolder).id,
    label: (value as WorkspaceFolder).label,
    children: (value as WorkspaceFolder).children.flatMap((child) => {
      const nextChild = normalizeWorkspaceFolder(child);
      return nextChild ? [nextChild] : [];
    }),
    files: (value as WorkspaceFolder).files.flatMap((file) => {
      const nextFile = normalizeWorkspaceFile(file);
      return nextFile ? [nextFile] : [];
    }),
  };
}

function hydrateWorkspaceFolders() {
  if (typeof window === 'undefined') {
    return createWorkspaceFolders();
  }

  try {
    const raw = window.localStorage.getItem(WORKSPACE_FOLDERS_STORAGE_KEY);

    if (!raw) {
      return createWorkspaceFolders();
    }

    const parsed = JSON.parse(raw) as unknown;

    if (!Array.isArray(parsed)) {
      return createWorkspaceFolders();
    }

    const normalizedFolders = parsed.flatMap((folder) => {
      const nextFolder = normalizeWorkspaceFolder(folder);
      return nextFolder ? [nextFolder] : [];
    });

    return normalizedFolders.length > 0
      ? stripGeneratedWorkspaceEntries(normalizedFolders)
      : createWorkspaceFolders();
  } catch {
    return createWorkspaceFolders();
  }
}

function hasFileDrag(types: readonly string[]) {
  return types.includes('Files');
}

function getUploadedFileTypeLabel(file: File) {
  if (file.type.trim().length > 0) {
    const subtype = file.type.split('/').at(-1) ?? file.type;
    return subtype.replace(/[-+]/g, ' ').toUpperCase();
  }

  const extension = file.name.includes('.') ? file.name.split('.').at(-1) ?? '' : '';
  return extension ? extension.toUpperCase() : 'FILE';
}

function formatUploadedFileSize(sizeBytes: number) {
  if (sizeBytes >= 1024 * 1024 * 1024) {
    return `${(sizeBytes / (1024 * 1024 * 1024)).toFixed(1)} GB`;
  }

  if (sizeBytes >= 1024 * 1024) {
    return `${(sizeBytes / (1024 * 1024)).toFixed(1)} MB`;
  }

  if (sizeBytes >= 1024) {
    return `${Math.max(1, Math.round(sizeBytes / 1024))} KB`;
  }

  return `${Math.max(1, sizeBytes)} B`;
}

function inferUploadedFileKind(fileName: string): WorkspaceFile['kind'] {
  const lowerName = fileName.trim().toLowerCase();

  if (lowerName.endsWith('.canvas') || lowerName.endsWith('.fig') || lowerName.endsWith('.sketch')) {
    return 'canvas';
  }

  if (
    lowerName.endsWith('.outline') ||
    lowerName.endsWith('.opml') ||
    lowerName.endsWith('.csv') ||
    lowerName.endsWith('.tsv')
  ) {
    return 'outline';
  }

  if (
    lowerName.endsWith('.md') ||
    lowerName.endsWith('.txt') ||
    lowerName.endsWith('.rtf') ||
    lowerName.endsWith('.doc') ||
    lowerName.endsWith('.docx')
  ) {
    return 'memo';
  }

  return 'brief';
}

function buildUploadedWorkspaceFile(file: File, index: number): WorkspaceFile {
  return {
    id: `uploaded-file-${Date.now()}-${index}-${Math.random().toString(36).slice(2, 8)}`,
    label: file.name,
    description: `Imported upload · ${getUploadedFileTypeLabel(file)} · ${formatUploadedFileSize(file.size)}`,
    kind: inferUploadedFileKind(file.name),
  };
}

function App() {
  const [folders, setFolders] = useState<WorkspaceFolder[]>(hydrateWorkspaceFolders);
  const [openFileId, setOpenFileId] = useState<string | null>(null);
  const [openFolderId, setOpenFolderId] = useState<string | null>('general-knowledge');
  const [folderView, setFolderView] = useState<'canvas' | 'explorer'>('canvas');
  const [isFileDropActive, setIsFileDropActive] = useState(false);
  const [hoveredSidebarItem, setHoveredSidebarItem] = useState<
    | {
        type: 'folder' | 'file';
        id: string;
      }
    | null
  >(null);
  const fileDragDepthRef = useRef(0);
  const activeFileSeedMatch = useMemo(
    () => (openFileId ? findFilePathById(folders, openFileId) : null),
    [folders, openFileId],
  );
  const activeFileSeed = activeFileSeedMatch?.file ?? null;
  const {
    activePage,
    pages,
    moveNodes,
    removeFilePage,
    resizeNode,
    addNode,
    updateNode,
    deleteNode,
    selectedNodeIds,
    setSelectedNodeIds,
    setView,
  } = useFilePages(activeFileSeed);
  const displayFolders = useMemo(
    () => mergeWorkerOutputsIntoFolders(folders, pages),
    [folders, pages],
  );
  const activeFileMatch = useMemo(
    () => (openFileId ? findFilePathById(displayFolders, openFileId) : null),
    [displayFolders, openFileId],
  );
  const activeFile = activeFileMatch?.file ?? activeFileSeed;
  const activeFolder = useMemo(
    () => (openFolderId ? findFolderById(displayFolders, openFolderId) : null),
    [displayFolders, openFolderId],
  );
  const activeFolderPath = useMemo(
    () => (openFolderId ? findFolderPathById(displayFolders, openFolderId) : null),
    [displayFolders, openFolderId],
  );
  const uploadTargetFolder = useMemo(() => {
    const directlyOpenFolder = openFolderId ? findFolderById(folders, openFolderId) : null;

    if (directlyOpenFolder) {
      return directlyOpenFolder;
    }

    if (activeFileSeedMatch) {
      return activeFileSeedMatch.folders.at(-1) ?? null;
    }

    const fallbackPathFolderId = activeFolderPath
      ?.slice()
      .reverse()
      .find((folder) => Boolean(findFolderById(folders, folder.id)))?.id;

    if (fallbackPathFolderId) {
      return findFolderById(folders, fallbackPathFolderId);
    }

    return folders[0] ?? null;
  }, [activeFileSeedMatch, activeFolderPath, folders, openFolderId]);
  const locationSegments = useMemo(
    () =>
      activeFileMatch
        ? [...activeFileMatch.folders.map((folder) => folder.label), activeFileMatch.file.label]
        : activeFolderPath?.map((folder) => folder.label) ?? [],
    [activeFileMatch, activeFolderPath],
  );
  const activeView = activeFile ? activePage?.view ?? null : activeFolder ? folderView : null;

  const handleFileDelete = useCallback(
    (fileId: string) => {
      removeFilePage(fileId);
      setOpenFileId((current) => (current === fileId ? null : current));
    },
    [removeFilePage],
  );

  const handleUploadFiles = useCallback((files: File[]) => {
    if (!uploadTargetFolder || files.length === 0) {
      return;
    }

    const uploadedFiles = files.map((file, index) => buildUploadedWorkspaceFile(file, index));

    setFolders((current) =>
      uploadedFiles.reduce(
        (nextFolders, file) => addFileToFolderById(nextFolders, uploadTargetFolder.id, file),
        current,
      ),
    );
  }, [uploadTargetFolder]);

  const handleAppDragEnter = useCallback((event: React.DragEvent<HTMLDivElement>) => {
    if (!hasFileDrag(Array.from(event.dataTransfer.types))) {
      return;
    }

    event.preventDefault();
    fileDragDepthRef.current += 1;
    setIsFileDropActive(true);
  }, []);

  const handleAppDragOver = useCallback((event: React.DragEvent<HTMLDivElement>) => {
    if (!hasFileDrag(Array.from(event.dataTransfer.types))) {
      return;
    }

    event.preventDefault();
    event.dataTransfer.dropEffect = 'copy';

    if (!isFileDropActive) {
      setIsFileDropActive(true);
    }
  }, [isFileDropActive]);

  const handleAppDragLeave = useCallback((event: React.DragEvent<HTMLDivElement>) => {
    if (!hasFileDrag(Array.from(event.dataTransfer.types))) {
      return;
    }

    event.preventDefault();
    fileDragDepthRef.current = Math.max(0, fileDragDepthRef.current - 1);

    if (fileDragDepthRef.current === 0) {
      setIsFileDropActive(false);
    }
  }, []);

  const handleAppDrop = useCallback((event: React.DragEvent<HTMLDivElement>) => {
    if (!hasFileDrag(Array.from(event.dataTransfer.types))) {
      return;
    }

    event.preventDefault();
    fileDragDepthRef.current = 0;
    setIsFileDropActive(false);

    handleUploadFiles(Array.from(event.dataTransfer.files));
  }, [handleUploadFiles]);

  useEffect(() => {
    window.localStorage.setItem(
      WORKSPACE_FOLDERS_STORAGE_KEY,
      JSON.stringify(stripGeneratedWorkspaceEntries(folders)),
    );
  }, [folders]);

  useEffect(() => {
    if (openFileId && !findFilePathById(displayFolders, openFileId)) {
      setOpenFileId(null);
    }
  }, [displayFolders, openFileId]);

  useEffect(() => {
    if (openFolderId && !findFolderById(displayFolders, openFolderId)) {
      setOpenFolderId(null);
    }
  }, [displayFolders, openFolderId]);

  useEffect(() => {
    if (activeView !== 'canvas') {
      setHoveredSidebarItem(null);
    }
  }, [activeView, activeFile?.id, activeFolder?.id]);

  return (
    <div
      className="relative min-h-screen"
      onDragEnter={handleAppDragEnter}
      onDragOver={handleAppDragOver}
      onDragLeave={handleAppDragLeave}
      onDrop={handleAppDrop}
    >
      <SidebarProvider
        defaultOpen
        style={
          {
            '--sidebar-width': '24rem',
            '--sidebar-width-icon': '4.25rem',
          } as React.CSSProperties
        }
        className="min-h-screen w-full bg-[radial-gradient(circle_at_top,_rgba(99,102,241,0.10),_transparent_30%),radial-gradient(circle_at_bottom_right,_rgba(14,165,233,0.08),_transparent_28%),linear-gradient(180deg,_#f8fbff_0%,_#f3f6fb_100%)]"
      >
        <WorkspaceSidebar
          folders={displayFolders}
          highlightedItem={hoveredSidebarItem}
          onFoldersChange={(nextFolders) => setFolders(stripGeneratedWorkspaceEntries(nextFolders))}
          onOpenFile={(fileId) => {
            setOpenFileId(fileId);
            setOpenFolderId(null);
          }}
          onOpenFolder={(folderId) => {
            setOpenFolderId(folderId);
            setOpenFileId(null);
          }}
          onFileDelete={handleFileDelete}
        />
        <SidebarInset className="min-h-screen bg-transparent md:peer-data-[variant=inset]:m-0 md:peer-data-[variant=inset]:rounded-none md:peer-data-[variant=inset]:shadow-none md:peer-data-[variant=inset]:peer-data-[state=collapsed]:ml-0">
          <div className="flex h-full min-h-screen flex-col">
            <FileWorkspace
              activeFile={activeFile}
              activeFolder={activeFolder}
              activeView={activeView}
              locationSegments={locationSegments}
              nodes={activePage?.nodes ?? []}
              selectedNodeIds={selectedNodeIds}
              onMoveNodes={moveNodes}
              onResizeNode={resizeNode}
              onAddNode={addNode}
              onUpdateNode={updateNode}
              onDeleteNode={deleteNode}
              onSelectNodes={setSelectedNodeIds}
              onHoveredSidebarItemChange={setHoveredSidebarItem}
              onViewChange={(view) => {
                if (activeFile) {
                  setView(view);
                  return;
                }

                setFolderView(view);
              }}
            />
          </div>
        </SidebarInset>
      </SidebarProvider>

      {isFileDropActive ? (
        <div className="pointer-events-none fixed inset-5 z-50 rounded-[2rem] border border-slate-300/75 bg-white/58 p-6 shadow-[0_32px_90px_-52px_rgba(15,23,42,0.35)] backdrop-blur-xl">
          <div className="flex h-full items-center justify-center rounded-[1.6rem] border border-slate-300/70 border-dashed bg-white/72">
            <div className="max-w-md text-center">
              <div className="mx-auto flex size-16 items-center justify-center rounded-[1.4rem] border border-slate-200/85 bg-white/92 shadow-[0_18px_40px_-28px_rgba(15,23,42,0.28)]">
                <UploadIcon className="size-7 text-slate-600" />
              </div>
              <div className="mt-5 text-[1.35rem] font-semibold tracking-[-0.02em] text-slate-950">
                Drop Files To Upload
              </div>
              <div className="mt-2 text-sm leading-6 text-slate-500">
                {uploadTargetFolder
                  ? `Files will be added to ${uploadTargetFolder.label}.`
                  : 'Files will be added to the current workspace.'}
              </div>
            </div>
          </div>
        </div>
      ) : null}
    </div>
  );
}

export default App;
